#' Test all column ordering and select the best one according to AOA
#'
#' @param Model  A class of 'varest' or 'vec2var'
#' @param Step Integer. Maximum number of iterations for first stage optimization using DEoptim
#' @param Bmat A (KxK) impact matrix of covariance matrix of reduced form errors, such that Bmat*Bmat'= Sigma_U / Identification matrix
#' @param Varname Character, names of variables in the systems
#' @param AOA List generated by function AOA.3d()
#'
#' @return A (KxK) impact matrix, which is the best according to AOA
#' @export eva.best
#' @importFrom combinat permn
#'
#' @examples NULL
eva.best <- function(Model, AOA, Step, Bmat, Varname){
  K        <- ncol(Bmat)
  perms    <- permn(K)
  score    <- rep(NA, length(perms))
  eva.test <- list()
  for (i in 1:length(perms)) {
    B.test        <- resign.mat(Bmat[,perms[[i]]], K = K)
    IRF.test      <- get.my.irf(Model = Model, Step = Step, Bmat = B.test, Normalize = TRUE, Varname = Varname)
    eva.test[[i]] <- Evaluate.AOA(IRF.test, AOA = AOA)
    score[i]      <- sum(eva.test[[i]])
  }
  eva.test[[which.max(score)]]
}

