#' Evaluate whether the identified IRFs lie in the Area Of Acceptance
#'
#' @param Irf (KxKxh) array generated by get.my.irf() function. IRF to be evaluated
#' @param AOA List generated by AOA.3d or AOA.4d
#'
#' @return a (KxKxh) array containing logical values, TRUE, if the identified IRFs lie in the Area Of Acceptance;
#' FALSE, otherwise.
#'
#' @export Evaluate.AOA
#'
#' @examples NULL
Evaluate.AOA <- function(Irf, AOA){
  Varname <- rownames(Irf)
  K       <- length(Varname)
  Step    <- dim(Irf)[3] - 1

  erg <- array(NA, c(K, K, Step + 1))
  for (h in 1:(Step + 1)) {
    for (i in 1:K) {
      for (j in 1:K) {
        erg[i,j,h] <- Irf[i,j,h] <= AOA$U[i,j,h] & Irf[i,j,h] >= AOA$L[i,j,h]
      }
    }
  }
  return(erg)
}
