#' Plot the True IRFs and AOA
#'
#' @param Irf.true a (KxKxh) array generated by get.my.irf() function. The "true" IRFs implied by the DGP parameters.
#' @param AOA List generated by AOA.AOA.DGP#
#'
#' @return Creat a ggplot object of class "gg"-"ggplot"
#'
#' @import ggplot2
#' @importFrom reshape2 melt
#' @importFrom dplyr left_join
#' @export plot.AOA
#'
#' @examples NULL
plot.AOA <- function(Irf.true, AOA){

  Varname <- rownames(Irf.true)
  K       <- length(Varname)
  Step    <- dim(Irf.true)[3] - 1
  c       <- 1

  Response           <- Response_L           <- Response_U           <- matrix(0, ncol = K^2 + 1, nrow = Step + 1)
  colnames(Response) <- colnames(Response_L) <- colnames(Response_U) <- rep("h", K^2 + 1)
  Response[,c]       <- Response_L[,c]       <- Response_U[,c]       <- 0:Step


  for(i in 1:K){
    for(j in 1:K){
      c <- c + 1
      Response[,c]   <- Irf.true[i,j,]
      Response_L[,c] <- AOA$L[i,j,]
      Response_U[,c] <- AOA$U[i,j,]

      colnames(Response)[c]   <- paste("epsilon[", j,"]", "%->%", Varname[i])
      colnames(Response_L)[c] <- colnames(Response_U)[c] <- colnames(Response)[c]
    }
  }

  Response   <- melt(as.data.frame(Response), id = 'h')
  Response_L <- melt(as.data.frame(Response_L), id = 'h', value.name = "L")
  Response_U <- melt(as.data.frame(Response_U), id = 'h', value.name = "U")

  Response_CI   <- left_join(Response_L, Response_U, by = c("variable", "h"))
  Response_plot <- left_join(Response, Response_CI, by = c("variable", "h"))

  erg <- ggplot(data = Response_plot, aes(x = h, y = value)) + geom_line() + geom_hline(yintercept = 0, color = 'red') +
    facet_wrap(~variable, scales = "free_y", labeller = label_parsed) +
    geom_ribbon(aes(ymin = L, ymax = U), alpha=0.3) +
    xlab("Horizon") + ylab("Response") +
    theme_bw()

  return(erg)
}
