#' Plot identification results of IRFs
#'
#' @param IRF.eva  A (KxKxh) array generated by functions simulate.**()
#'
#' @return Creat a ggplot object of class "gg"-"ggplot"
#' @import ggplot2
#' @importFrom reshape2 melt
#' @export plot.simu
#'
#' @examples NULL
plot.simu <- function(IRF.eva){

  Varname <- row.names(IRF.eva)
  K       <- dim(IRF.eva)[1]
  Step    <- dim(IRF.eva)[3] - 1

  Performance           <- matrix(0, ncol = K^2 + 1, nrow = Step + 1)
  colnames(Performance) <- rep("h", K^2 + 1)
  c                     <- 1
  Performance[,c]       <- 0:Step

  for(i in 1:K){
    for(j in 1:K){
      c                        <- c + 1
      Performance[,c]          <- IRF.eva[i,j,]
      colnames(Performance)[c] <- paste("epsilon[", j,"]", "%->%", Varname[i])
    }
  }
  Performance <- melt(as.data.frame(Performance), id = 'h')

  erg <- ggplot(data = Performance, aes(x = h, y = value)) + geom_line(linetype = "dotted") +
    geom_point(shape = 0, color="darkred", size=3) + geom_hline(yintercept = 0, color = 'red') +
    facet_wrap(~variable, scales = "free_y", labeller = label_parsed) +
    xlab("Horizon") + ylab(" ") + ylim(0, 1) + theme_bw()
  return(erg)
}
