#' Identification and evaluation based on Sign restrictions
#'
#' @param Data List containing simulated data
#' @param AOA List generated by function AOA.3d()
#' @param Iter Integer, number of rotations
#' @param Signmat Matrix, a (KxK) matrix containing Sign restrictions. 1: positive sign; -1: negative sign; NA: unrestricted
#' @param RHorizont Integer, RHorizonts of impulse responses, for which the sign restrictions are imposed
#' @param PositiveDiag Logical, if PositiveDiag = TRUE, the diagonal of impact matrix will be forced to be positive
#' @param Ci Double, between [0,1] sample quantiles for IRFs
#' @param Plot Logical, if Plot = TRUE, a plot of identification performance will be created#' @param Subsample Vector, a (1x2) vector containing start- and end-point of subsamples that will be
#' subject to estimation and identification
#' @param Varname Character, names of variables in the systems
#' @param Subsample
#' @param MT  Logical, if MT = TRUE, Fry and Pagan’s (2011) median target (MT) method will be used
#' @param Itermax Integer, number of maximum draws
#' @param Hist Logical, if Hist = TRUE, histogram of distribution of freqencies of detecting the correct sign for the unrestricted elements in the identified B matrices is provided
#' @param TrueSign Matrix, a (KxK) matrix containing the true Sign pattern in DGP 1: positive sign; -1: negative sign
#' @param Bmat Matrix of dimension (KxK), the true structural decomposition implied by the DGP
#'
#' @return A (KxKxh) array containing proportion of all simulated IRFs that lie in the AOA
#' @export simulate.sign
#'
#' @examples NULL
simulate.sign <- function(Data, AOA, Subsample = NULL, Iter, Itermax, Signmat, TrueSign, RHorizont,
                          MT = FALSE, PositiveDiag = TRUE, Ci, Varname = c("x", "pi", "r"), Bmat,
                          Plot = FALSE, Hist = FALSE){

  Size     <- length(Data)
  K        <- ncol(Data[[1]]$Y)
  p        <- 2
  Tob      <- nrow(Data[[1]]$Y)
  Step     <- dim(AOA$L)[3] - 1
  eva.temp <- array(NA, c(K, K, Step + 1, Size))
  mse.temp <- matrix(rep(NA, Size*3), nrow = Size, ncol = 3)

  # check whether to use Fry and Pagan’s (2011) Median Target method
  if (MT) {
    eva.temp.MT   <- eva.temp
  }

  # check btw. full sign restriction or argnostic sign restriction in the sense of Uhlig(2005)
  nosign <- which(is.na(Signmat))
  if (length(nosign) == 0) {
    agnostic <- FALSE
  } else if (length(nosign) == 1) {
    agnostic <- TRUE
    correct  <- rep(NA, Size)
    unclear  <- rep(NA, Size)
  } else {stop("For now, only one unrestricted sign is allowed.")}

  start.time <- Sys.time()
  cat("\r", "...calculating finish time...")

  for (i in 1:Size) {
    # Data-generation
    Y.temp <- Data[[i]]

    # Subsample
    if (!is.null(Subsample)){
      Y.temp$Y     <- Y.temp$Y[Subsample[1]:Subsample[2],]
      Y.temp$shock <- Y.temp$shock[Subsample[1]:Subsample[2],]
      Y.temp$iv    <- Y.temp$iv[Subsample[1]:Subsample[2],]
    }

    # Estimation
    var2 <- vars::VAR(Y.temp$Y, p = 2, type = "none")

    # Identification
    ID.temp               <- get.id.Sign(Model = var2, Iter = Iter, Itermax = Itermax, Signmat = Signmat, RHorizont = RHorizont, MT = MT, PositiveDiag = PositiveDiag, Step = Step, Ci = Ci)
    if (!is.null(ID.temp)) {
      IRF.temp            <- ID.temp$IRF.M
      row.names(IRF.temp) <- Varname
      eva.temp[,,,i]      <- Evaluate.AOA(IRF.temp, AOA = AOA)
      mse.temp[i,]         <- eva.RMSE(B = Bmat, Bhat = apply(ID.temp$Bs, c(1,2), median), xcol = 3)

      # document frequency of detection of the correct sign
      if (agnostic) {
        unclear[i] <- ID.temp$unrest$Unclear
        if (TrueSign[nosign] == 1){
          correct[i] <- ID.temp$unrest$Positive
        } else if (TrueSign[nosign] == -1) {
          correct[i] <- ID.temp$unrest$Negative
        } else {stop("Invalid argument in TrueSign!")}
      }

      # evaluate MT method
      if (MT) {
        IRF.temp.MT            <- ID.temp$IRF.MT
        row.names(IRF.temp.MT) <- Varname
        eva.temp.MT[,,,i]      <- Evaluate.AOA(IRF.temp.MT, AOA = AOA)
      }

    } else {
      eva.temp[,,,i]      <- array(FALSE, dim = c(K, K, Step + 1))
    }

    # print progress
    progress(i, max = Size, start.time = start.time)
  }

  if (MT){
    erg.M <- erg.MT <- array(NA, c(K, K, Step + 1))
    for (h in 1:(Step + 1)) {
      for (i in 1:K) {
        for (j in 1:K) {
          erg.M[i,j,h]  <- mean(eva.temp[i,j,h,])
          erg.MT[i,j,h] <- mean(eva.temp.MT[i,j,h,])
        }
      }
    }

    row.names(erg.M) <- Varname
    row.names(erg.MT) <- Varname

    erg <- list("M" = erg.M, "MT" = erg.MT, "ump" = NaN, "mse.mp" = colMeans(mse.temp, na.rm = T))

    if (Plot == TRUE){
      plot(plot.simu.multi(list(erg.M, erg.MT), Label = c("Median", "Median Target")))
    }
  } else {
    erg.M <- array(NA, c(K, K, Step + 1))
    for (h in 1:(Step + 1)) {
      for (i in 1:K) {
        for (j in 1:K) {
          erg[i,j,h] <- mean(eva.temp[i,j,h,])
        }
      }
    }
    row.names(erg) <- Varname

    erg <- list("M" = erg.M, "ump" = NaN, "mse.mp" = colMeans(mse.temp, na.rm = T))

    if (Plot == TRUE){
      plot(plot.simu(erg))
    }
  }

  if (agnostic) {
    entry <- which(is.na(Signmat), arr.ind = T)
    cat(paste0("\n", "Frequency of detecting the correct sign pattern at position ",
               "row " , entry[1], " column ", entry[2], ": ",
               round(mean(correct)*100, digits = 2), " percent.", "\n"))
    erg[["unrest"]] <- list("position" = entry, "freq" = correct, "freq_mean" = mean(correct), "Unclear" = mean(unclear))
    if (Hist) {
      plot(ggplot(data = as.data.frame(correct), aes(x = correct)) + labs(x= "") +
             geom_histogram(bins = 20, colour = "black", fill = "#FF6666", alpha = 0.1) +
             geom_vline(aes(xintercept = mean(correct)), color = "deepskyblue", linetype = "dashed", size = 1) +
             theme_bw())
    }
  }

  return(erg)
}
