#' Plot and compare results from multiple identification methodes
#'
#' @param IRF.evas List, contains multiple (KxKxh) arrays generated by functions simulate.**()
#' @param Label Character, names of identification methods
#' @param shape_manual If provided, point shapes are set manually. It should contain set of aesthetic values
#' to map data values to. If this is a named vector, then the values will be matched based on the names.
#' If unnamed, values will be matched in order (usually alphabetical) with the limits of the scale.
#' Any data values that don't match will be given na.value.
#' @param level_manual change levels of factors
#'
#' @return Creat a ggplot object of class "gg"-"ggplot"
#' @import ggplot2
#' @importFrom reshape2 melt
#' @importFrom tibble add_column
#' @export plot.simu.multi
#'
#' @examples NULL
#'
plot.simu.multi <- function(IRF.evas, Label = NULL, shape_manual = NULL, level_manual = NULL){

  if (is.null(Label)) {
    erg <- plot.simu(IRF.evas)
    return(erg)
  }

  N <- length(Label)

  if (N == 1){
    erg <- plot.simu(IRF.evas)
    return(erg)
  }

  Varname <- row.names(IRF.evas[[1]])
  K       <- dim(IRF.evas[[1]])[1]
  Step    <- dim(IRF.evas[[1]])[3] - 1

  Performance           <- matrix(0, ncol = K^2 + 1, nrow = Step + 1)
  colnames(Performance) <- rep("h", K^2 + 1)
  c                     <- 1
  Performance[,c]       <- 0:Step

  for(i in 1:K){
    for(j in 1:K){
      c                        <- c + 1
      Performance[,c]          <- IRF.evas[[1]][i,j,]
      colnames(Performance)[c] <- paste("epsilon[", j,"]", "%->%", Varname[i])
    }
  }
  Performance <- melt(as.data.frame(Performance), id = 'h') %>% add_column(Methods = Label[1])

  for (n in 2:N) {
    Performance.temp           <- matrix(0, ncol = K^2 + 1, nrow = Step + 1)
    colnames(Performance.temp) <- rep("h", K^2 + 1)
    c                          <- 1
    Performance.temp[,c]       <- 0:Step
    for(i in 1:K){
      for(j in 1:K){
        c                             <- c + 1
        Performance.temp[,c]          <- IRF.evas[[n]][i,j,]
        colnames(Performance.temp)[c] <- paste("epsilon[", j,"]", "%->%", Varname[i])
      }
    }

    Performance.temp <- melt(as.data.frame(Performance.temp), id = 'h') %>% add_column(Methods = Label[n])

    Performance <- rbind(Performance, Performance.temp)
  }

  if (!is.null(level_manual)){
    Performance$Methods <- factor(  Performance$Methods, levels = level_manual)
  }

  erg <- ggplot(data = Performance, aes(x = h, y = value, group = Methods)) + geom_line(aes(linetype = Methods, color = Methods)) +
    geom_point(aes(shape = Methods, color = Methods), size=3) + geom_hline(yintercept = 0, color = 'red') +
    facet_wrap(~variable, scales = "free_y", labeller = label_parsed) +
    xlab("Horizon") + ylab(" ") + ylim(0, 1) + theme_bw()

  if (!is.null(shape_manual)){
    erg <- erg + scale_shape_manual(values = shape_manual)
  }

  return(erg)
}
