#' Calculate dcov and cvm distance of choleski and optimized decompositions
#'
#' @param u T by K data matrix.
#' @param Bmat K by K optimized decomposition matrix.
#' @param dd Object of class 'indepTestDist' (generated by 'indepTest' from package 'copula').
#'
#' @return dcov and cvm distance of choleski and optimized decompositions
#' @export test.indep
#'
#' @examples NULL
test.indep <- function(u, Bmat, dd = NULL){
  if ( is.null(dd) ){
    dd <- copula::indepTestSim(nrow(u), ncol(u), verbose = F)
  }
  SigmaU     <- crossprod(u) / (nrow(u) - 1)
  Chol       <- t(chol(SigmaU))
  eps.chol   <- solve(Chol)%*%t(u) %>% t()
  stat.chol  <- c(steadyICA::multidcov(eps.chol), copula::indepTest(eps.chol, dd)$global.statistic)
  eps.opt    <- solve(Bmat)%*%t(u) %>% t()
  stat.opt   <- c(steadyICA::multidcov(eps.opt), copula::indepTest(eps.opt, dd)$global.statistic)
  erg        <- data.frame(stat.chol, stat.opt)
  row.names(erg) <- c("dcov.stat", "cvm.stat")
  return(erg)
}
